services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq-host
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  gameserver:
    build:
      context: .
      dockerfile: Dockerfile.Server
    container_name: game-server
    ports:
      - "50052:50051"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    command: ["./server-game-app"]

  dbserver:
    build:
      context: .
      dockerfile: Dockerfile.ServerDB
    container_name: db-server
    ports:
      - "9988:9988"
    command: ["./server-db"]

  mqserver:
    build:
      context: .
      dockerfile: Dockerfile.ServerMQ
    container_name: mq-server
    command: ["./server-mq"]
    ports:
      - "9000:9000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
